### ISSUE TITLE
kernelsu并未参与编译

### ISSUE THREAD

**Issue by zl521368789** [netPokey/kernelsu_xiaomi_sdm845#1]
我拉取你的代码按照你的方法进行编译，发现一个问题，kernelsu并未参与编译，最后报错
fs/built-in.o: In function `SyS_faccessat':
ram_core.c:(.text+0x1330): undefined reference to `ksu_handle_faccessat'
fs/built-in.o: In function `vfs_read':
ram_core.c:(.text+0x355c): undefined reference to `ksu_vfs_read_hook'
ram_core.c:(.text+0x3568): undefined reference to `ksu_vfs_read_hook'
ram_core.c:(.text+0x3660): undefined reference to `ksu_handle_vfs_read'
fs/built-in.o: In function `vfs_fstatat':
ram_core.c:(.text+0x99c0): undefined reference to `ksu_handle_stat'
fs/built-in.o: In function `do_execveat_common':
ram_core.c:(.text+0xc13c): undefined reference to `ksu_execveat_hook'
ram_core.c:(.text+0xc148): undefined reference to `ksu_execveat_hook'
ram_core.c:(.text+0xc180): undefined reference to `ksu_handle_execveat_sucompat'
ram_core.c:(.text+0xc494): undefined reference to `ksu_handle_execveat'

**Comment by netPokey** [comment]
你编译的哪个手机的内核

**Comment by zl521368789** [comment]
> 你编译的哪个手机的内核

小米mix3和mix2s都进行了尝试

**Comment by zl521368789** [comment]
已经编译出来了，重新拉份就成功了，不会是昨天kernelsu的脚本有问题吧

**Comment by netPokey** [comment]
没有问题的 我的kernel 代码没有进行过修改
